-- create 10 records for price table with attributes vehicleId, price, currency
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (1, 10000, 'USD');
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (2, 20000, 'USD');
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (3, 30000, 'USD');
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (4, 40000, 'USD');
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (5, 50000, 'USD');
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (6, 60000, 'USD');
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (7, 70000, 'USD');
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (8, 80000, 'USD');
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (9, 90000, 'USD');
INSERT INTO PRICE (VEHICLE_ID, PRICE, CURRENCY) VALUES (10, 100000, 'USD');